```{r}
library(readr)
library(dplyr)
library(ggplot2)
str(midwest)
head(midwest)
summary(midwest)
```
```{r}
missing_values <- sapply(midwest, function(x) sum(is.na(x)))
print(missing_values)
```
```{r}
# Visualize the data
# Histogram for numerical variables
num_vars <- sapply(midwest, is.numeric)
num_data <- midwest[, num_vars]
```

```{r}
# boxplot
ggplot(midwest, aes(x =state, y =popdensity)) +
  geom_boxplot(fill = "orange", color = "black") +
  theme_minimal() +
  labs(title = "Boxplot of Humidity by midwest", x= "state", y= "popdensity")
```
```{r}
# Scatter plot to show the relationship between two numeric variables (replace 'temp' and 'humidity' with appropriate column names)
ggplot(midwest, aes(x = state, y = popdensity)) +
  geom_point(color = "red") +
  theme_minimal() +
  labs(title = "Scatter Plot of state vs popdensity", x = "state", y = "popdensity")
```

```{r}
# Time series plot for a variable over time (replace 'date' and 'temp' with appropriate column names)
ggplot(midwest, aes(x = state , y = popdensity)) +
  geom_line(color = "blue") +
  theme_minimal() +
  labs(title = "midwest", x = "state", y = "popdensity")
```
